In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('../main/log/random_study_complex_20250812.csv', header = None, names = ['Seed', 'Mutation', 
                                                                           'T1 nodes', 'T1 nodes as', 'T1 k_complexity', 'T1 sb_complexity',
                                                                           'T1 sharpness', 
                                                                           'T2 nodes', 'T2 nodes as', 'T2 k_complexity', 'T2 sb_complexity', 
                                                                           'T2 sharpness',
                                                                           'Mut nodes', 'Mut nodes as', 'Mut k_complexity', 'Mut sb_complexity',
                                                                           'Mut sharpness'])

In [3]:
data.head(12)

,Seed,Mutation,T1 nodes,T1 nodes as,T1 k_complexity,T1 sb_complexity,T1 sharpness,T2 nodes,T2 nodes as,T2 k_complexity,T2 sb_complexity,T2 sharpness,Mut nodes,Mut nodes as,Mut k_complexity,Mut sb_complexity,Mut sharpness
0,0,S1,7,7,42,1.982851e+05,0.616754,NaN,NaN,NaN,NaN,NaN,19,54,107,5805.613517,0.999536
1,0,ABS,7,7,42,1.982851e+05,0.616754,NaN,NaN,NaN,NaN,NaN,16,14,96,3269.158485,0.948199
2,0,S2,7,7,42,1.982851e+05,0.616754,7.0,9.0,48.0,171028.405245,0.897967,29,31,120,4444.136102,0.995048
3,1,S1,7,9,48,3.419950e+06,0.193915,NaN,NaN,NaN,NaN,NaN,19,16,109,1732.847987,0.996375
4,1,ABS,7,9,48,3.419950e+06,0.193915,NaN,NaN,NaN,NaN,NaN,16,16,97,1086.522161,0.990344
5,1,S2,7,9,48,3.419950e+06,0.193915,7.0,8.0,52.0,381796.464500,0.993160,29,30,116,1126.364001,0.883451
6,2,S1,7,7,51,1.022062e+05,0.996963,NaN,NaN,NaN,NaN,NaN,19,54,109,8683.878519,0.999823
7,2,ABS,7,7,51,1.022062e+05,0.996963,NaN,NaN,NaN,NaN,NaN,16,14,99,3497.507653,0.923795
8,2,S2,7,7,51,1.022062e+05,0.996963,7.0,8.0,52.0,36375.255695,0.884991,29,32,126,37736.999721,0.992364
9,3,S1,7,7,45,2.132320e+06,0.996652,NaN,NaN,NaN,NaN,NaN,19,46,109,5119.542032,0.970759
10,3,ABS,7,7,45,2.132320e+06,0.996652,NaN,NaN,NaN,NaN,NaN,16,14,99,1087.239999,0.878617
11,3,S2,7,7,45,2.132320e+06,0.996652,7.0,9.0,47.0,126579.587095,0.234742,29,31,121,2147.071366,0.922629

In [4]:
data['T1 nodes as'] = data.apply(lambda x: x['T1 nodes as'] if x['T1 nodes'] >= x['T1 nodes as'] else x['T1 nodes'], axis = 1)
data['T2 nodes as'] = data.apply(lambda x: x['T2 nodes as'] if x['T2 nodes'] >= x['T2 nodes as'] else x['T2 nodes'], axis = 1)
data['Mut nodes as'] = data.apply(lambda x: x['Mut nodes as'] if x['Mut nodes'] >= x['Mut nodes as'] else x['Mut nodes'], axis = 1)

In [5]:
data.head(12)

,Seed,Mutation,T1 nodes,T1 nodes as,T1 k_complexity,T1 sb_complexity,T1 sharpness,T2 nodes,T2 nodes as,T2 k_complexity,T2 sb_complexity,T2 sharpness,Mut nodes,Mut nodes as,Mut k_complexity,Mut sb_complexity,Mut sharpness
0,0,S1,7,7,42,1.982851e+05,0.616754,NaN,NaN,NaN,NaN,NaN,19,19,107,5805.613517,0.999536
1,0,ABS,7,7,42,1.982851e+05,0.616754,NaN,NaN,NaN,NaN,NaN,16,14,96,3269.158485,0.948199
2,0,S2,7,7,42,1.982851e+05,0.616754,7.0,7.0,48.0,171028.405245,0.897967,29,29,120,4444.136102,0.995048
3,1,S1,7,7,48,3.419950e+06,0.193915,NaN,NaN,NaN,NaN,NaN,19,16,109,1732.847987,0.996375
4,1,ABS,7,7,48,3.419950e+06,0.193915,NaN,NaN,NaN,NaN,NaN,16,16,97,1086.522161,0.990344
5,1,S2,7,7,48,3.419950e+06,0.193915,7.0,7.0,52.0,381796.464500,0.993160,29,29,116,1126.364001,0.883451
6,2,S1,7,7,51,1.022062e+05,0.996963,NaN,NaN,NaN,NaN,NaN,19,19,109,8683.878519,0.999823
7,2,ABS,7,7,51,1.022062e+05,0.996963,NaN,NaN,NaN,NaN,NaN,16,14,99,3497.507653,0.923795
8,2,S2,7,7,51,1.022062e+05,0.996963,7.0,7.0,52.0,36375.255695,0.884991,29,29,126,37736.999721,0.992364
9,3,S1,7,7,45,2.132320e+06,0.996652,NaN,NaN,NaN,NaN,NaN,19,19,109,5119.542032,0.970759
10,3,ABS,7,7,45,2.132320e+06,0.996652,NaN,NaN,NaN,NaN,NaN,16,14,99,1087.239999,0.878617
11,3,S2,7,7,45,2.132320e+06,0.996652,7.0,7.0,47.0,126579.587095,0.234742,29,29,121,2147.071366,0.922629

In [6]:
data[['Mutation', 'Mut nodes', 'Mut nodes as', 'Mut k_complexity', 'Mut sb_complexity', 'Mut sharpness']].groupby('Mutation').median().T

Mutation                   ABS           S1           S2
Mut nodes            16.000000    19.000000    29.000000
Mut nodes as         15.000000    19.000000    29.000000
Mut k_complexity     99.000000   109.000000   122.000000
Mut sb_complexity  4243.349612  7615.330886  5540.288893
Mut sharpness         0.940743     0.990459     0.986956

In [7]:
data[['Mut nodes', 'Mut nodes as', 'Mut k_complexity', 'Mut sb_complexity', 'Mut sharpness']].corr()

,Mut nodes,Mut nodes as,Mut k_complexity,Mut sb_complexity,Mut sharpness
Mut nodes,1.000000,0.955170,0.945808,0.021866,0.036087
Mut nodes as,0.955170,1.000000,0.921548,0.023788,0.030585
Mut k_complexity,0.945808,0.921548,1.000000,0.011836,0.034870
Mut sb_complexity,0.021866,0.023788,0.011836,1.000000,0.010009
Mut sharpness,0.036087,0.030585,0.034870,0.010009,1.000000